### ISSUE TITLE
not compatible with adapter-static

### ISSUE THREAD

**Issue by Upsetmania** [jmagrippis/techy-cat#30]
hello thank you for your great work, I would like to make it work with adapter-static but I find no solution for the compiled can you help me? thank you

**Comment by jmagrippis** [comment]
Hello @Upsetmania, thanks for reaching out!

This app is just not... **static** I'm afraid: given we have the server-side auth and proper backend endpoints that do stuff... such as the form actions but also some standalone endpoints!

We have pages we do not want to pre-render as they present content custom to the logged-in user, and we have endpoints that execute javascript! The `adapter-static` is for sites that only do html in the end.

If you remove the hooks file and, like, all routes... you may get something that builds, but at that point wouldn't you rather start with one of the proper starters with the SvelteKit wizard? (`npm create svelte@latest my-app`)

--

Another question would be, why do you want to use the `adapter-static`, what problem are you trying to solve? 🙂

**Comment by Upsetmania** [comment]
hello, yes I understand, I saw that we couldn't because of the pre-render + server no problem, I wanted html pages for the seo thank you again

**Comment by jmagrippis** [comment]
No worries!

I thought that might be a reason, but it's worth saying this app **does** get rendered "in HTML" which is "SEO-friendly": that's the whole point of doing things server-side, and not on mount! You wouldn't get an "html" benefit by pre-rendering. The pages are html already. The server renders them as html, and there is no further javascript which adds things to the DOM.

"Pre-render" would do the same thing, only it will do it during the build step once, and have no execution on the server. This may result in faster serving of the html, which is a different thing! You could get that "pre-render" benefit without that adapter, by caching heavily for example!

Also worth noting server-rendered doesn't necessarily mean great SEO! So it may be worth investigating SEO further and if it was someone else who told you "do it in html for SEO", maybe challenging them to see what they mean and why they think that 🙂
